---
cidr_networks:
  container: 172.29.236.0/22
  tunnel: 172.29.240.0/22
  storage: 172.29.244.0/22


used_ips:
  - "172.29.236.1,172.29.236.255"
  - "172.29.240.1,172.29.240.255"
  - "172.29.244.1,172.29.244.255"


global_overrides:
  internal_lb_vip_address: 172.29.236.6
  external_lb_vip_address: 192.168.122.6
  tunnel_bridge: "br-vxlan"
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"
        ip_from_q: "container"
        type: "raw"
        group_binds:
          - all_containers
          - hosts
        is_container_address: true
        is_ssh_address: true
    - network:
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "10000:21000"
        net_name: "vxlan"
        group_binds:
          - neutron_linuxbriege_agent
    - network:
        container_bridge: "br-ex"
        container_type: "veth"
        container_interface: "eth12"
        host_bind_override: "eth12"
        type: "flat"
        net_name: "provider"
        group_binds:
          - neutron_openvswitch_agent
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "storage"
        type: "raw"
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute
          - ceph-osd
          - ceph-rgw


# galera, memcache, rabbitmq, utility
shared-infra_hosts:
  controller1:
    ip: 172.29.236.6

# repository (apt cache, python packages, etc)
repo-infra_hosts:
  controller1:
    ip: 172.29.236.6

# load balancer
haproxy_hosts:
  controller1:
    ip: 172.29.236.6

###
### OpenStack
###

# keystone
identity_hosts:
  controller1:
    ip: 172.29.236.6

# cinder api services
storage-infra_hosts:
  controller1:
    ip: 172.29.236.6

# glance
image_hosts:
  controller1:
    ip: 172.29.236.6

# nova api, conductor, etc services
compute-infra_hosts:
  controller1:
    ip: 172.29.236.6

# heat
orchestration_hosts:
  controller1:
    ip: 172.29.236.6

# horizon
dashboard_hosts:
  controller1:
    ip: 172.29.236.6

# neutron server, agents (L3, etc)
network_hosts:
  controller1:
    ip: 172.29.236.6

# nova hypervisors
compute_hosts:
  compute1:
    ip: 172.29.236.12

# cinder storage host (LVM-backed)
storage_hosts:
  controller1:
    ip: 172.29.236.6

placement-infra_hosts:
  controller1:
    ip: 172.29.236.6

ceph-mon_hosts:
  controller1:
    ip: 172.29.236.6

ceph-rgw_hosts:
  controller1:
    ip: 172.29.236.6

ceph-osd_hosts:
  ceph1:
    ip: 172.29.236.13
    container_vars:
      devices:
        - /dev/vdb
        - /dev/vdc
        - /dev/vdd

manila-infra_hosts:
  controller1:
    ip: 172.29.236.6

octavia-infra_hosts:
  controller1:
    ip: 172.29.236.6

