---
cidr_networks:
  management: 172.29.236.0/22
  tunnel: 172.29.240.0/22
  storage: 172.29.244.0/22

used_ips:
  - "172.29.236.1,172.29.236.20"
  - "172.29.240.1,172.29.240.20"
  - "172.29.244.1,172.29.244.20"


global_overrides:
  internal_lb_vip_address: 172.29.236.6
  external_lb_vip_address: 10.10.0.6 
  lb_name: controller
  tunnel_bridge: "br-vxlan"
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        group_binds:
          - all_containers
          - hosts
        type: "raw"
        container_bridge: "br-mgmt"
        container_interface: "eth1"
        container_type: "veth"
        ip_from_q: "management"
        is_container_address: true
        is_ssh_address: true
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth6"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "1:600"
        net_name: "vxlan"
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth11"
        type: "vlan"
        range: "1:1"
        net_name: "vlan"
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-ex"
        container_type: "veth"
        container_interface: "eth12"
        host_bind_override: "eth3"
        type: "flat"
        net_name: "flat"
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "storage"
        type: "raw"
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute


# Shared infrastructure parts
shared-infra_hosts:
  controller-01:
    ip: 172.29.236.6

# User defined Repository Hosts, this is an optional group
repo-infra_hosts:
  controller-01:
    ip: 172.29.236.6

haproxy_hosts:
  controller-01:
    ip: 172.29.236.6

identity_hosts:
  controller-01:
    ip: 172.29.236.6

# OpenStack Compute infrastructure parts
os-infra_hosts:
  controller-01:
    ip: 172.29.236.6

# Keystone Identity infrastructure parts

# glance
image_hosts:
  controller-01:
    ip: 172.29.236.6

# nova api, conductor, etc services
compute-infra_hosts:
  controller-01:
    ip: 172.29.236.6

# OpenStack Storage infrastructure parts
storage-infra_hosts:
  controller-01:
    ip: 172.29.236.6

# horizon
dashboard_hosts:
  controller-01:
    ip: 172.29.236.6

# nova-compute
compute_hosts:
  compute-01:
    ip: 172.29.236.13

# neutron-server
network_hosts:
  controller-01:
    ip: 172.29.236.6

placement-infra_hosts:
  controller-01:
    ip: 172.29.236.6


